# Generated by Django 5.2.4 on 2025-08-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_course_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
