# Generated by Django 5.2.5 on 2025-08-26 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('midterm', 'منتصف الفصل'), ('final', 'نهائي'), ('quiz', 'اختبار قصير'), ('homework', 'واجب منزلي')], max_length=20, verbose_name='نوع الدرجة')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة')),
                ('date_given', models.DateField(blank=True, null=True, verbose_name='تاريخ إعطاء الدرجة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_app_grades', to='courses.course', verbose_name='الدورة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_app_grades', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'درجات',
                'unique_together': {('student', 'course', 'grade_type')},
            },
        ),
    ]
