# Generated by Django 5.2.5 on 2025-08-26 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدورة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الدورة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'دورات',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='الدورة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'تسجيلات',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('midterm', 'منتصف الفصل'), ('final', 'نهائي'), ('quiz', 'اختبار قصير'), ('homework', 'واجب منزلي')], max_length=20, verbose_name='نوع الدرجة')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to='courses.course', verbose_name='الدورة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'درجات',
                'unique_together': {('student', 'course', 'grade_type')},
            },
        ),
    ]
